'use strict';
const M=window.PDFModel,$=s=>document.querySelector(s);
let doc={version:3,title:'Mitt dokument',header:M.band(false),footer:M.band(true),blockGap:5,numbers:true,pages:[{id:M.uid(),blocks:[]}]};
let active=doc.pages[0].id,selected=null,dirty=false,imageTarget=null,logoTarget=null;
function make(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e}
function btn(text,fn,cls){const e=make('button',cls,text);e.type='button';e.onclick=e=>{e.stopPropagation();fn(e)};return e}
function notify(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').style.display='none',5500)}
function changed(){dirty=true}
function selection(){const p=doc.pages.find(p=>p.id===selected?.p),b=p?.blocks.find(b=>b.id===selected.b);return {p,b,c:b?.cells[selected.c]}}
function syncActive(){document.querySelectorAll('.pagewrap').forEach(w=>w.querySelector('.paper').classList.toggle('active',w.id===active));document.querySelectorAll('#pageNav button').forEach((e,i)=>e.classList.toggle('active',doc.pages[i].id===active))}
function select(p,b,i){active=p.id;selected={p:p.id,b:b.id,c:i};syncActive();document.querySelectorAll('.cell').forEach(e=>e.classList.toggle('selected',e.dataset.block===b.id&&Number(e.dataset.cell)===i));properties()}
function addPage(){if(doc.pages.length>=100){notify('Ett projekt kan innehålla högst 100 sidor.');return}const p={id:M.uid(),blocks:[]};doc.pages.push(p);active=p.id;selected=null;changed();render();document.getElementById(p.id).scrollIntoView({behavior:'smooth',block:'start'});return p.id}
function addLayout(type,pid=active){const p=doc.pages.find(p=>p.id===pid);if(!p||!M.layouts[type])throw Error('Ogiltig layout eller sida');const available=M.contentHeight(doc)-M.usedHeight(p,doc)-(p.blocks.length?doc.blockGap:0),b=M.createBlock(type,available);if(!b){notify('Sidan är full. Lägg till en ny sida.');return false}p.blocks.push(b);active=p.id;selected={p:p.id,b:b.id,c:0};changed();render();return true}
Object.entries(M.layouts).forEach(([type,l])=>{const e=btn('',()=>addLayout(type),'template');e.draggable=true;e.setAttribute('aria-label',l.label);e.ondragstart=ev=>{ev.dataTransfer.setData('text/plain',type);ev.dataTransfer.effectAllowed='copy'};const mini=make('span','mini');mini.style.gridTemplateColumns=`repeat(${l.cols},1fr)`;mini.style.gridTemplateRows=`repeat(${l.rows},1fr)`;l.cells.forEach(([x,y,w,h])=>{const box=make('i');box.style.gridColumn=`${x+1} / span ${w}`;box.style.gridRow=`${y+1} / span ${h}`;mini.append(box)});e.append(mini,make('span','',l.label));$('#templates').append(e)});
function styleText(t,c){t.style.fontSize=c.size+'pt';t.style.fontWeight=c.bold?'700':'400';t.style.textAlign=c.align;t.style.hyphens=c.hyphens?'auto':'manual';t.style.webkitHyphens=c.hyphens?'auto':'manual';t.style.lineHeight=c.lineHeight;t.dataset.textStyle=c.textStyle}
function styleImage(img,c){img.style.objectFit=c.fit;img.style.objectPosition=`${c.posX}% ${c.posY}%`;img.style.transform=`scale(${c.zoom})`;img.style.transformOrigin=`${c.posX}% ${c.posY}%`}
function updateCell(){const {b,c}=selection();if(!b)return;const e=document.querySelector(`.cell[data-block="${b.id}"][data-cell="${selected.c}"]`);if(c.type==='text')styleText(e.querySelector('.textcontent'),c);if(c.type==='image')styleImage(e.querySelector('img'),c);changed();checkOverflow()}
function plainPaste(e){e.preventDefault();const text=e.clipboardData.getData('text/plain'),sel=window.getSelection();if(!sel.rangeCount)return;const range=sel.getRangeAt(0);if(!e.currentTarget.contains(range.commonAncestorContainer))return;range.deleteContents();const node=document.createTextNode(text);range.insertNode(node);range.setStartAfter(node);range.collapse(true);sel.removeAllRanges();sel.addRange(range);e.currentTarget.dispatchEvent(new Event('input',{bubbles:true}))}
function render(){
  $('#pages').replaceChildren();$('#pageNav').replaceChildren();
  doc.pages.forEach((p,index)=>{
    const nav=btn(String(index+1),()=>{active=p.id;syncActive();document.getElementById(p.id).scrollIntoView({behavior:'smooth',block:'start'})},p.id===active?'active':'');nav.setAttribute('aria-label',`Välj sida ${index+1}`);$('#pageNav').append(nav);
    const wrap=make('div','pagewrap');wrap.id=p.id;const top=make('div','pagetop');top.append(make('span','',`SIDA ${String(index+1).padStart(2,'0')}`));const remove=btn('Ta bort sida',()=>{if(!confirm('Ta bort sidan och dess innehåll?'))return;doc.pages=doc.pages.filter(x=>x.id!==p.id);active=doc.pages[0].id;selected=null;changed();render()});remove.disabled=doc.pages.length===1;top.append(remove);
    const holder=make('div','paperholder'),paper=make('article','paper'+(p.id===active?' active':''));paper.setAttribute('aria-label',`A4 sida ${index+1}`);paper.onclick=()=>{active=p.id;syncActive()};paper.ondragover=e=>{if(e.dataTransfer.types.includes('text/plain')){e.preventDefault();paper.classList.add('dragover')}};paper.ondragleave=()=>paper.classList.remove('dragover');paper.ondrop=e=>{e.preventDefault();paper.classList.remove('dragover');const t=e.dataTransfer.getData('text/plain');if(M.layouts[t])addLayout(t,p.id)};
    paper.style.paddingTop=M.contentTop(doc)+'mm';paper.style.paddingBottom=(doc.footer.enabled?25:15)+'mm';const content=make('div','pagecontent');content.style.height=M.contentHeight(doc)+'mm';content.style.gap=doc.blockGap+'mm';if(!p.blocks.length){const empty=make('div','empty');empty.append(make('strong','','Din nästa sida börjar här'),make('p','','Dra in en layout från innehållscentret'));content.append(empty)}
    p.blocks.forEach(b=>{
      const block=make('div','block');block.dataset.id=b.id;const l=M.layouts[b.type];
      b.cells.forEach((c,i)=>{
        const e=make('div','cell');e.dataset.block=b.id;e.dataset.cell=i;const [x,y,w,h]=l.cells[i];e.style.gridColumn=`${x+1} / span ${w}`;e.style.gridRow=`${y+1} / span ${h}`;if(selected?.b===b.id&&selected.c===i)e.classList.add('selected');e.onclick=ev=>{ev.stopPropagation();select(p,b,i)};
        if(c.type==='empty'){const choose=make('div','cellchooser');choose.append(btn('T  Text',()=>{c.type='text';selected={p:p.id,b:b.id,c:i};active=p.id;changed();render();document.querySelector('.cell.selected .textcontent').focus()}),btn('▧  Bild',()=>{imageTarget={p:p.id,b:b.id,c:i};$('#imageInput').click()}));e.append(choose)}
        if(c.type==='text'){const t=make('div','textcontent',c.text);t.contentEditable='true';t.lang='sv';t.setAttribute('role','textbox');t.setAttribute('aria-label','Text i ruta');t.setAttribute('aria-multiline','true');styleText(t,c);t.onfocus=()=>select(p,b,i);t.oninput=()=>{c.text=t.innerText;changed();checkOverflow()};t.onpaste=plainPaste;e.append(t)}
        if(c.type==='image'){const img=make('img');img.src=c.src;img.alt='Dokumentbild';img.draggable=false;styleImage(img,c);e.append(img)}block.append(e);
      });
      addHandles(block,p,b);content.append(block);applyGrid(block,b);
    });
    paper.append(content);for(const name of ['header','footer'])if(doc[name].enabled)paper.append(renderBand(name,index));holder.append(paper);wrap.append(top,holder);$('#pages').append(wrap);
  });scale();properties();syncBandControls();requestAnimationFrame(checkOverflow);
}
function scale(){const available=Math.max(200,$('main').clientWidth-48),z=Math.min(Number($('#zoom').value),available/793.7008);document.querySelectorAll('.paperholder').forEach(h=>{h.style.width=793.7008*z+'px';h.style.height=1122.5197*z+'px';h.firstChild.style.transform=`scale(${z})`})}
window.addEventListener('resize',scale);$('#zoom').onchange=scale;
function applyGrid(el,b){
  M.fitGaps(b);el.style.height=b.height+'mm';el.style.columnGap=b.gapX+'mm';el.style.rowGap=b.gapY+'mm';el.style.gridTemplateColumns=b.cols.map(v=>`minmax(0,${v}fr)`).join(' ');el.style.gridTemplateRows=b.rows.map(v=>`minmax(0,${v}fr)`).join(' ');
  const px=96/25.4,dimensions={cols:180*px,rows:b.height*px},gaps={cols:b.gapX*px,rows:b.gapY*px};
  const start=(axis,i)=>b[axis].slice(0,i).reduce((a,v)=>a+v,0)*(dimensions[axis]-gaps[axis]*(b[axis].length-1))+gaps[axis]*i;
  const end=(axis,i)=>start(axis,i)+b[axis][i]*(dimensions[axis]-gaps[axis]*(b[axis].length-1));
  el.querySelectorAll('.divider').forEach(h=>{const axis=h.dataset.axis,i=Number(h.dataset.index),other=axis==='cols'?'rows':'cols',first=Number(h.dataset.start),count=Number(h.dataset.count),pos=end(axis,i)+gaps[axis]/2,from=start(other,first),length=end(other,first+count-1)-from;Object.assign(h.style,axis==='cols'?{left:pos+'px',top:from+'px',height:length+'px',bottom:'auto'}:{top:pos+'px',left:from+'px',width:length+'px',right:'auto'});h.setAttribute('aria-valuenow',Math.round(b[axis].slice(0,i+1).reduce((a,v)=>a+v,0)*100))});
  el.querySelector('.height-handle').setAttribute('aria-valuenow',Number(b.height.toFixed(1)));
}
function addHandles(el,p,b){
  const handle=(axis,i,segment=[0,1],part=0)=>{const h=make('div',axis==='height'?'height-handle':'divider '+axis);Object.assign(h.dataset,{axis,index:i,start:segment[0],count:segment[1]});h.tabIndex=0;h.setAttribute('role','separator');h.setAttribute('aria-orientation',axis==='cols'?'vertical':'horizontal');h.setAttribute('aria-label',(axis==='height'?'Ändra blockhöjd':axis==='cols'?`Ändra kolumnbredd ${i+1}`:`Ändra radhöjd ${i+1}`)+(part?` del ${part+1}`:''));h.title='Dra för att ändra storlek · piltangenter för finjustering';h.setAttribute('aria-valuemin',axis==='height'?'0.1':'0');h.setAttribute('aria-valuemax',axis==='height'?M.maxHeight(p,b,doc):'100');
    const finish=()=>{changed();properties();checkOverflow()};
    h.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();select(p,b,selected?.b===b.id?selected.c:0);h.setPointerCapture(e.pointerId);const rect=el.getBoundingClientRect(),factor=rect.width/(180*96/25.4),start=axis==='cols'?e.clientX:e.clientY,original=axis==='height'?b.height:[...b[axis]],originalGap=b.gapY;h.classList.add('dragging');
      const move=ev=>{const delta=(axis==='cols'?ev.clientX:ev.clientY)-start;if(axis==='height'){b.height=M.clamp(original+delta/factor*25.4/96,.1,M.maxHeight(p,b,doc));b.gapY=originalGap;M.fitGaps(b)}else{const gap=axis==='cols'?b.gapX:b.gapY,length=(axis==='cols'?rect.width:rect.height)-(b[axis].length-1)*gap*96/25.4*factor;b[axis]=M.resizeTracks(original,i,delta/Math.max(.001,length))}applyGrid(el,b);changed();checkOverflow()};
      const end=()=>{h.removeEventListener('pointermove',move);h.removeEventListener('pointerup',end);h.removeEventListener('pointercancel',end);h.classList.remove('dragging');finish()};h.addEventListener('pointermove',move);h.addEventListener('pointerup',end);h.addEventListener('pointercancel',end);
    };
    h.onkeydown=e=>{const positive=axis==='cols'?'ArrowRight':'ArrowDown',negative=axis==='cols'?'ArrowLeft':'ArrowUp';if(![positive,negative].includes(e.key))return;e.preventDefault();select(p,b,selected?.b===b.id?selected.c:0);const delta=e.key===positive?1:-1;if(axis==='height'){b.height=M.clamp(b.height+delta*(e.shiftKey?1:.1),.1,M.maxHeight(p,b,doc));M.fitGaps(b)}else b[axis]=M.resizeTracks(b[axis],i,delta*(e.shiftKey?.05:.001));applyGrid(el,b);finish()};el.append(h);
  };
  for(const axis of ['cols','rows'])for(let i=0;i<b[axis].length-1;i++)M.dividerSegments(M.layouts[b.type],axis,i).forEach((segment,part)=>handle(axis,i,segment,part));handle('height',0);
}
function properties(){
  const root=$('#properties');root.replaceChildren();const {p,b,c}=selection();$('#selectionTitle').textContent=b?M.layouts[b.type].label:'Din arbetsyta';if(!b){root.append(make('p','muted','Välj en ruta för text- och bildinställningar. Dra i de blå rutgränserna för att ändra storlek.'));return}
  function control(label,el){const l=make('label','',label);l.append(el);root.append(l);return el}
  function number(label,value,min,max,step,change){const e=make('input');e.type='number';Object.assign(e,{value,min,max,step});e.onchange=()=>{const v=M.clamp(Number.isFinite(e.valueAsNumber)?e.valueAsNumber:min,min,max);e.value=v;change(v)};return control(label,e)}
  function selectControl(label,value,options,change){const e=make('select');options.forEach(([v,t])=>{const o=make('option','',t);o.value=v;e.append(o)});e.value=value;e.onchange=()=>change(e.value);return control(label,e)}
  function range(label,value,min,max,step,change){const e=make('input');e.type='range';e.setAttribute('aria-label',label);Object.assign(e,{value,min,max,step});const out=make('output','',String(value));const l=make('label','range-label');l.append(make('span','',label),out,e);e.oninput=()=>{out.textContent=e.value;change(Number(e.value))};root.append(l)}
  number('Blockhöjd (mm)',Number(b.height.toFixed(1)),.1,M.maxHeight(p,b,doc),.1,v=>{b.height=v;M.fitGaps(b);changed();render()});
  number('Mellanrum vågrätt (mm)',Number(b.gapX.toFixed(1)),0,M.gapLimit(b,'x'),.1,v=>{b.gapX=v;changed();render()});
  number('Mellanrum lodrätt (mm)',Number(b.gapY.toFixed(1)),0,M.gapLimit(b,'y'),.1,v=>{b.gapY=v;changed();render()});root.append(make('p','hint','Dra i gränserna eller nederkanten. Höjd kan anges ned till 0,1 mm. Mellanrum minskas om de inte får plats.'));
  const order=make('div','row');const move=dir=>{const i=p.blocks.indexOf(b),j=i+dir;if(j<0||j>=p.blocks.length)return;[p.blocks[i],p.blocks[j]]=[p.blocks[j],p.blocks[i]];changed();render()};const up=btn('↑ Flytta',()=>move(-1)),down=btn('↓ Flytta',()=>move(1));up.disabled=p.blocks[0]===b;down.disabled=p.blocks.at(-1)===b;order.append(up,down);root.append(order);
  if(c.type==='text'){
    root.append(make('h3','','Text'));
    selectControl('Textstil',c.textStyle,Object.entries(M.styles).map(([k,v])=>[k,v.label]),v=>{c.textStyle=v;Object.assign(c,{size:M.styles[v].size,bold:M.styles[v].bold});updateCell();properties()});
    number('Textstorlek (pt)',c.size,8,64,1,v=>{c.size=v;updateCell()});
    const bold=btn('Fetstil',()=>{c.bold=!c.bold;updateCell();properties()},c.bold?'primary wide':'wide');bold.setAttribute('aria-pressed',String(c.bold));root.append(bold);
    selectControl('Textjustering',c.align,[['left','Vänster'],['center','Centrerad'],['right','Höger'],['justify','Marginaljusterad']],v=>{c.align=v;updateCell()});
    number('Radavstånd',c.lineHeight,1,2,.05,v=>{c.lineHeight=v;updateCell()});
    const hy=make('input');hy.type='checkbox';hy.checked=c.hyphens;hy.onchange=()=>{c.hyphens=hy.checked;updateCell()};const label=make('label','check');label.append(hy,document.createTextNode('Avstava automatiskt'));root.append(label,make('p','hint','Svensk avstavning använder webbläsarens språkstöd. Inställningarna gäller hela textrutan.'));
  }
  if(c.type==='image'){
    root.append(make('h3','','Bild'),btn('Byt bild',()=>{imageTarget={...selected};$('#imageInput').click()},'wide'));
    selectControl('Bildanpassning',c.fit,[['cover','Fyll rutan (beskär)'],['contain','Visa hela bilden'],['fill','Sträck till rutan']],v=>{c.fit=v;updateCell()});
    range('Zoom (%)',Math.round(c.zoom*100),100,300,1,v=>{c.zoom=v/100;updateCell()});range('Vågrätt läge (%)',c.posX,0,100,1,v=>{c.posX=v;updateCell()});range('Lodrätt läge (%)',c.posY,0,100,1,v=>{c.posY=v;updateCell()});
    root.append(make('p','hint','Flytta motivet med lägesreglagen. ”Sträck” kan förvränga bilden.'),btn('Återställ bildanpassning',()=>{Object.assign(c,{fit:'cover',zoom:1,posX:50,posY:50});updateCell();properties()},'wide'));
  }
  if(c.type!=='empty')root.append(btn('Töm vald ruta',()=>{if(!confirm('Töm rutans innehåll?'))return;b.cells[selected.c]=M.cell();changed();render()},'wide clearcell'));
  root.append(btn('Ta bort layoutblock',()=>{if(!confirm('Ta bort layoutblocket?'))return;p.blocks=p.blocks.filter(x=>x!==b);selected=null;changed();render()},'danger'));
}
function checkOverflow(){let bad=false;document.querySelectorAll('.textcontent').forEach(t=>{const over=t.scrollHeight>t.clientHeight+2||t.scrollWidth>t.clientWidth+2;t.parentElement.classList.toggle('overflow',over);t.setAttribute('aria-invalid',String(over));bad ||=over});document.querySelectorAll('.page-band').forEach(f=>{const text=f.querySelector('.band-text');const over=text.scrollHeight>text.clientHeight+2||text.scrollWidth>text.clientWidth+2;f.classList.toggle('overflow',over);bad ||=over});return bad}
function renderBand(name,index){
  const cfg=doc[name],band=make('div','page-band page-'+name+(cfg.logoPosition==='right'?' logo-right':''));
  if(cfg.logo){const image=make('img','band-logo');image.src=cfg.logo;image.alt=name==='header'?'Logotyp i sidhuvud':'Logotyp i sidfot';image.style.width=cfg.logoWidth+'mm';band.append(image)}
  band.append(make('div','band-text',cfg.text));if(name==='footer'&&doc.numbers)band.append(make('span','pagenumber',`${index+1} / ${doc.pages.length}`));return band;
}
function syncBandControls(){for(const name of ['header','footer']){const cfg=doc[name];$('#'+name+'Enabled').checked=cfg.enabled;$('#'+name+'Controls').hidden=!cfg.enabled;$('#'+name+'Text').value=cfg.text;$('#'+name+'Width').value=cfg.logoWidth;$('#'+name+'Position').value=cfg.logoPosition;$('#'+name+'RemoveLogo').hidden=!cfg.logo;const thumb=$('#'+name+'LogoPreview');thumb.hidden=!cfg.logo;if(cfg.logo)thumb.src=cfg.logo;else thumb.removeAttribute('src')}$('#blockGap').value=doc.blockGap;$('#numbers').checked=doc.numbers}
function refreshBands(){document.querySelectorAll('.paper').forEach((paper,i)=>{paper.querySelectorAll('.page-band').forEach(e=>e.remove());for(const name of ['header','footer'])if(doc[name].enabled)paper.append(renderBand(name,i))});changed();checkOverflow()}
for(const name of ['header','footer']){
  $('#'+name+'Enabled').onchange=e=>{const previous=doc[name].enabled;doc[name].enabled=e.target.checked;const bad=doc.pages.findIndex(p=>M.usedHeight(p,doc)>M.contentHeight(doc)+.01);if(bad>=0){doc[name].enabled=previous;e.target.checked=previous;notify(`Sida ${bad+1} behöver mer plats. Minska ett block eller flytta innehåll innan du aktiverar ${name==='header'?'sidhuvudet':'sidfoten'}.`);return}changed();render()};
  $('#'+name+'Text').oninput=e=>{doc[name].text=e.target.value;refreshBands()};
  $('#'+name+'Width').oninput=e=>{doc[name].logoWidth=Number(e.target.value);refreshBands()};
  $('#'+name+'Position').onchange=e=>{doc[name].logoPosition=e.target.value;refreshBands()};
  $('#'+name+'AddLogo').onclick=()=>{logoTarget=name;$('#logoInput').click()};
  $('#'+name+'RemoveLogo').onclick=()=>{doc[name].logo='';changed();render()};
}
$('#blockGap').onchange=e=>{const old=doc.blockGap;doc.blockGap=M.clamp(Number(e.target.value)||0,0,20);if(doc.pages.some(p=>M.usedHeight(p,doc)>M.contentHeight(doc)+.01)){doc.blockGap=old;e.target.value=old;notify('Mellanrummet ryms inte på alla sidor. Minska blockhöjden först.');return}changed();render()};
async function readLocalImage(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024)throw Error('Välj PNG, JPEG eller WebP, högst 20 MB.');const bitmap=await createImageBitmap(file);const ratio=Math.min(1,2400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/png')}
$('#logoInput').onchange=async e=>{const file=e.target.files[0],target=logoTarget;e.target.value='';if(!file||!target)return;try{const src=await readLocalImage(file);doc[target].logo=src;changed();render()}catch(error){notify(error.message||'Bilden kunde inte öppnas.')}};
$('#title').oninput=e=>{doc.title=e.target.value;document.title=doc.title||'PDF Maker';changed()};$('#numbers').onchange=e=>{doc.numbers=e.target.checked;changed();render()};$('#addPage').onclick=addPage;$('#bottomAdd').onclick=addPage;
$('#imageInput').onchange=async e=>{const file=e.target.files[0],target=imageTarget;e.target.value='';if(!file||!target)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024){notify('Välj en PNG-, JPEG- eller WebP-bild, högst 20 MB.');return}try{const bitmap=await createImageBitmap(file);const ratio=Math.min(1,2400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const c=doc.pages.find(p=>p.id===target.p)?.blocks.find(b=>b.id===target.b)?.cells[target.c];if(!c)return;Object.assign(c,{type:'image',src:canvas.toDataURL('image/png'),zoom:1,posX:50,posY:50});selected=target;active=target.p;changed();render()}catch{notify('Bilden kunde inte öppnas. Prova en annan fil.')}};
$('#save').onclick=()=>{const blob=new Blob([JSON.stringify(doc)],{type:'application/json'}),url=URL.createObjectURL(blob),a=make('a');a.href=url;a.download=(doc.title||'dokument').replace(/[<>:"/\\|?*]/g,'_')+'.pdfmaker.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);dirty=false;notify('Projektfilen har laddats ner.')};$('#load').onclick=()=>$('#projectInput').click();
$('#projectInput').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;if(dirty&&!confirm('Öppna projektet och ersätta ditt osparade arbete?'))return;try{if(f.size>100*1024*1024)throw Error();doc=M.validate(JSON.parse(await f.text()));active=doc.pages[0].id;selected=null;$('#title').value=doc.title;$('#numbers').checked=doc.numbers;document.title=doc.title||'PDF Maker';dirty=false;render();notify('Projektet är öppnat.')}catch{notify('Filen är inte ett giltigt PDF Maker-projekt.')}};
$('#export').onclick=()=>{document.activeElement?.blur();if(checkOverflow()){notify('Texten ryms inte. Öka rutans storlek, minska textstorleken eller korta sidhuvudet/sidfoten innan export.');return}document.title=doc.title||'Mitt dokument';window.print()};window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
render();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const tool of [{name:'read_document_structure',description:'Read page and layout counts in the current PDF document.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({pages:doc.pages.map((p,i)=>({page:i+1,layouts:p.blocks.map(b=>b.type)}))})},{name:'add_document_page',description:'Append a blank A4 page to the current document.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:input=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected empty object');const id=addPage();if(!id)throw Error('Page limit reached');return {pages:doc.pages.length}}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort())}
